### ISSUE TITLE
Mind sharing how you modified the db_lang.bytes file?

### ISSUE THREAD

**Issue by dsxragnarok** [re4ever/Kor_File#1]
Hi, would you mind sharing how the db_lang.bytes was modified? I'd like to see if it's possible to do the same for English.

**Comment by re4ever** [comment]
![db_lang_structure](https://github.com/re4ever/Kor_File/assets/16168963/81fcd31c-1f28-4ad6-9d57-8a7d872bdf51)

These are data-structure in db_lang.bytes. 
If you may just want to get db_lang.bytes by EN-Machine-Translated, I can make one for you in few days. Good luck to you.

**Comment by dsxragnarok** [comment]
Yes that was what I was thinking of doing. If you can get it for me that'd be awesome too!

**Comment by re4ever** [comment]
Hi, I just uploaded db_lang.bytes EN-translated.

Check this wiki
https://github.com/re4ever/Kor_File/wiki/(SOC)-How-to

if you find a problem, create a new issue page and fill out the issue.

**Comment by dsxragnarok** [comment]
Great! Thank you.
