### ISSUE TITLE
db_lang.bytes files have embedded git diffs

### ISSUE THREAD

**Issue by dsxragnarok** [re4ever/Kor_File#2]
Hi,

It looks like the new updated db_lang.bytes for both kor and eng have embedded git diffs in them. 

![Screenshot 2023-11-16 at 9 25 07 AM](https://github.com/re4ever/Kor_File/assets/4951506/cf2ed307-e5b3-429d-9893-173364b4381a)
<img width="1792" alt="Screenshot 2023-11-16 at 9 24 38 AM" src="https://github.com/re4ever/Kor_File/assets/4951506/c1cbb683-efca-4ed8-b6c9-5f941b8ac5e1">

**Comment by re4ever** [comment]
Sorry, I'll fix and upload file by tomorrow

**Comment by re4ever** [comment]
I just uploaded fixed file. sorry about that.

**Comment by dsxragnarok** [comment]
Great! Thank you.
